apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: sops
spec:
  init:
    command: ["sh", "-c"]
    args:
      - |
        find . -type f \( -name '*.secret.yaml' -o -name 'secret.yaml' \) \
          -exec sops --decrypt --in-place {} \;

  discover:
    find:
      command: ["sh", "-c", "find . -name '*.secret.yaml' -o -name 'secret.yaml'"]

  generate:
    command: ["sh", "-c"]
    args:
      - |
        if [ -f kustomization.yaml ]; then
          kustomize build ${ACS_KUSTOMIZE_OPTIONS:-} .
        else
          find . -name '*.yaml' -print0 | xargs -0 cat
        fi