discover:
  find:
    command:
      - sh
      - -c
      - |
        find . \( -name '*.secret.yaml' -o -name 'secret.yaml' \) | grep .

generate:
  command:
    - sh
    - -c
    - |
      find . \( -name '*.secret.yaml' -o -name 'secret.yaml' \) -exec sops --decrypt --in-place {} \;

      if [ -f kustomization.yaml ]; then
        kustomize build .
      else
        find . -name '*.yaml' -print0 | xargs -0 cat
      fi